'use strict';
const state={page:'workbench',tab:'results',data:null,job:null,draft:'',workflow:'compare',source:null,explanation:'',general:'',busy:false};
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',spark:'<path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6L12 3Z"/>',chart:'<path d="M4 4v16h17M7 15l4-5 4 3 5-7"/>',book:'<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H4V4Zm16 0h-4a3 3 0 0 0-3 3v14a4 4 0 0 1 4-3h3V4Z"/>',box:'<path d="m12 3 9 5-9 5-9-5 9-5Zm9 5v10l-9 4-9-4V8m9 5v9M7 5l9 5"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',file:'<path d="M5 3h9l5 5v13H5V3Zm9 0v6h5M8 13h8m-8 4h6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<path d="m5 12 4 4 10-10"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',cloud:'<path d="M6 18a5 5 0 1 1 0-10 7 7 0 0 1 13 2 4 4 0 0 1-1 8H6Z"/>',folder:'<path d="M3 6h7l2 3h9v11H3V6Z"/>',layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>'};
const icon=(name,size=17)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.grid}</svg>`;
const labels={queued:'Queued',running:'Running',plan_review:'Plan review',needs_input:'Needs clarification',code_review:'Code review',result_review:'Awaiting review',accepted:'Accepted',rejected:'Rejected',changes_requested:'Changes requested',blocked:'Blocked',interrupted:'Interrupted',cancelled:'Cancelled'};
const badge=(text,type='neutral')=>`<span class="badge ${type}">${e(text)}</span>`;
const statusBadge=status=>badge(labels[status]||status,status==='accepted'?'green':['plan_review','code_review','result_review','blocked','interrupted','needs_input'].includes(status)?'amber':status==='running'?'blue':'neutral');
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',6500)}
async function api(path,body){const r=await fetch('/api'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':state.data?.token||''},body:JSON.stringify(body)});const v=await r.json();if(r.status===403&&body!==undefined){const fresh=await fetch('/api/bootstrap');if(fresh.ok){state.data=await fresh.json();throw Error('The local session restarted. Your work is saved; please retry this action.')}}if(!r.ok)throw Error(typeof v.detail==='string'?v.detail:JSON.stringify(v.detail));return v}
async function refresh(){state.data=await api('/bootstrap');if(state.job)state.job=await api('/jobs/'+state.job.id);render()}
function nav(page,label,name,count=''){return `<button class="navitem ${state.page===page?'active':''}" data-page="${page}">${icon(name)}${label}${count?`<span class="count">${count}</span>`:''}</button>`}
function render(){if(!state.data)return;const d=state.data;document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">${icon('layers',24)}</div><div>Engineering AI<small>Workbench</small></div></div><button class="new" data-action="new">${icon('plus',15)} New analysis</button><div class="navlabel">WORKSPACE</div>${nav('workbench','Conversations','spark')}${nav('agents','Agents','grid')}${nav('schedules','Schedules','clock')}${nav('jobs','Job history','clock',d.jobs.length)}<div class="navlabel">CAPABILITIES</div>${nav('workflows','Guided workflows','chart')}${nav('skills','Skills library','book')}${nav('tools','Tools','settings')}${nav('data-sources','Data sources','folder')}${nav('plugins','Plugins','box')}${nav('knowledge','Reviewed knowledge','layers')}${nav('source','Source discovery','code')}<div class="navlabel">CONTROL</div>${nav('governance','Security & permissions','shield')}${nav('models','Models & runtime','settings')}${nav('channels','Channels','cloud')}<div class="navlabel">CONVERSATIONS</div>${(d.conversations||[]).slice(0,4).map(c=>`<button class="recent" data-conversation="${c.id}">${e(c.title)}</button>`).join('')}<div class="navlabel">RECENT ANALYSES</div>${d.jobs.slice(0,3).map(j=>`<button class="recent ${j.id===state.job?.id?'active':''}" data-job="${e(j.id)}">${j.extension?'Moving-average comparison':'Compare analysis runs'}</button>`).join('')}<div class="side-bottom"><span class="local-dot"></span><span class="tiny">Local processing</span><p>Engineering context stays here.</p><span class="prototype">WORKING PROTOTYPE · 0.4</span><div class="user"><span class="avatar">DR</span><div>Demo reviewer<p>Single-user session</p></div></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumbs">${icon('folder',15)} Engineering projects <span>/</span><strong>Response validation</strong></div><div class="top-right">${badge('Synthetic data','neutral')}${badge('● Local workspace','green')}<span class="avatar">DR</span></div></header><div class="page">${pages[state.page]()}<div class="footer-note">Engineering AI Workbench · Functional prototype · Synthetic application and data · Human-reviewed results</div></div></main></div>`}
const head=(eyebrow,title,sub,actions='')=>`<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${actions}</div>`;
function chart(result,axes=false){const a=result.points_a,b=result.points_b,all=[...a,...b];let min=Math.min(...all.map(p=>p[1])),max=Math.max(...all.map(p=>p[1]));const pad=(max-min)*.12;min-=pad;max+=pad;const xmin=a[0][0],xmax=a[a.length-1][0];const X=x=>42+(x-xmin)/(xmax-xmin)*402,Y=y=>202-(y-min)/(max-min)*168;const path=pts=>pts.map((p,i)=>`${i?'L':'M'}${X(p[0]).toFixed(2)},${Y(p[1]).toFixed(2)}`).join(' ');return `<svg class="chart" viewBox="0 0 470 245" role="img" aria-label="Response curves for synthetic Run A and Run B">${Array.from({length:5},(_,i)=>{let y=min+(max-min)*i/4;return `<line x1="42" y1="${Y(y)}" x2="444" y2="${Y(y)}" stroke="#edf1f1"/><text x="33" y="${Y(y)+3}" text-anchor="end" fill="#8b9ca0" font-size="9">${y.toFixed(1)}</text>`}).join('')}${[0,20,40,60,80,100].map(x=>`<text x="${X(x)}" y="220" text-anchor="middle" fill="#8b9ca0" font-size="9">${x}</text>`).join('')}<text x="243" y="242" text-anchor="middle" fill="#8b9ca0" font-size="9">Sample</text>${axes?'<path d="M42 34 V202 H444" fill="none" stroke="#52666b" stroke-width="1.5" aria-label="X and Y axis lines"/>':''}<path d="${path(a)}" fill="none" stroke="#078a8c" stroke-width="2.3"/><path d="${path(b)}" fill="none" stroke="#7484c0" stroke-width="1.7"/></svg><div class="legend"><span><i></i>Run A · baseline</span><span><i class="blue"></i>Run B · revision</span></div>`}
function workbench(){const j=state.job;return head('ENGINEERING WORKSPACE',j?'Compare analysis runs':'From question to reviewed result',j?'Response validation / Run A and Run B':'Bring your engineering tools, workflows, and evidence into one place.',`<button class="btn" data-page="source">${icon('code',14)} Explore source</button>`)+`<div class="workspace"><section class="panel"><div class="panel-head"><div><h3>${icon('spark',15)} Analysis assistant</h3><p>${state.data.models.local.configured?'Local model available for explanations':'Deterministic demo · no model required'}</p></div>${j?statusBadge(j.status):badge('Ready','green')}</div><div class="context-strip">Inputs <span class="filetag">${icon('file',11)} Run A</span><span class="filetag">${icon('file',11)} Run B</span><span>via engineering application adapter</span></div><div class="chat">${j?conversation(j):welcome()}</div><div class="composer"><textarea id="request" aria-label="Analysis request" placeholder="Describe your analysis request…">${e(state.draft)}</textarea><div class="compose-controls"><select id="workflow" class="select" aria-label="Workflow"><option value="compare" ${state.workflow==='compare'?'selected':''}>Sample: released run comparison</option><option value="extension" ${state.workflow==='extension'?'selected':''}>Sample: moving-average extension</option></select><button class="btn primary" data-action="run" ${state.busy?'disabled':''}>Run analysis ${icon('arrow',13)}</button></div><p class="tiny muted" style="margin-top:12px">These are bundled sample workflows. Additional executable workflows require an approved integration; free-form text does not add new operations.</p></div></section><section class="panel"><div class="panel-head"><div><h3>${j?.result?'Difference report':'Results & evidence'}</h3><p>${j?.result?'Versioned inputs. Reproducible calculations.':'Your analysis becomes a reviewable artifact.'}</p></div>${j?.result?badge(j.status==='accepted'?'Accepted':'Draft',j.status==='accepted'?'green':'amber'):icon('chart',18)}</div>${rightPanel(j)}</section></div>`}
function welcome(){return `<div class="message assistant"><div class="avatar assistant-avatar">${icon('spark',15)}</div><div><div class="message-label">WORKBENCH</div><h2 class="welcome-title">What would you like to analyze?</h2><p class="welcome-copy">Try a sample workflow below using synthetic data. These examples demonstrate how analysis produces evidence for review.</p></div></div><div class="suggestions"><button class="suggestion" data-example="compare">Compare Run A against Run B ${icon('arrow',12)}<small>Sample workflow · released comparison</small></button><button class="suggestion" data-example="extension">Smooth the difference between runs ${icon('arrow',12)}<small>Sample workflow · reviewed Python extension</small></button></div><div class="callout">${icon('shield',13)} The engineering application owns the binary format. Python receives only its validated exports.</div>`}
function conversation(j){return `<div class="message"><div class="avatar">DR</div><div class="bubble">${e(j.request)}</div></div><div class="message assistant"><div class="avatar assistant-avatar">${icon('spark',15)}</div><div class="bubble"><div class="message-label">WORKBENCH</div>${j.status==='accepted'?'The report is accepted. You can now propose this workflow as a reusable skill.':j.status==='result_review'?'The comparison is ready. Numerical checks passed; please review the report before accepting it.':j.status==='code_review'?'The existing comparison method is reusable. The additional moving-average routine needs your code review before it can run.':j.status==='blocked'?'The job paused at a blocked step. Its inputs and checkpoint are saved.':j.status==='changes_requested'?'Changes were requested. Start a new analysis with the revised request to preserve this review record.':j.status==='cancelled'?'This job was cancelled at its checkpoint.':j.status==='rejected'?'The proposed script was rejected. No extension code was executed.':'The job is progressing through the approved workflow.'}</div></div><div class="steps">${j.events.filter(x=>!['request','review','skill','local_model'].includes(x.stage)).map(x=>`<div class="step"><span class="step-dot">${x.stage==='blocked'?'!':'✓'}</span>${e(x.detail)}<small>${new Date(x.at*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')}${['running','queued'].includes(j.status)?'<div class="step"><span class="step-dot"><span class="spinner"></span></span>Processing the next step…</div>':''}</div>${j.error?`<div class="callout amber">${e(j.error)}</div>`:''}${j.status==='code_review'?`<div class="callout amber">${e(j.draft_source||'Bundled example draft')}. Approval is bound to this script, the input snapshots, and the configured worker image.</div>`:''}${['blocked','interrupted'].includes(j.status)?'<div class="code-actions"><button class="btn primary" data-action="resume">Resume checkpoint</button><button class="btn" data-action="cancel">Cancel job</button></div>':''}${j.status==='accepted'?'<div class="code-actions"><button class="btn" data-action="promote">'+icon('book',13)+' Propose reusable skill</button></div>':''}`}
function rightPanel(j){if(j?.status==='code_review')return `<div class="panel-body"><div class="row">${badge('Pre-execution review','amber')}${badge('Read-only inputs')}</div><h3 style="margin-top:18px">Moving-average extension</h3><p class="subtitle">Read the exact Python script. It will run only in the configured Docker worker.</p><pre class="source-code">${e(j.script)}</pre><dl class="metadata"><dt>Input scope</dt><dd>Run A + Run B export snapshots</dd><dt>Execution</dt><dd>No network · non-root · 256 MB · 30 seconds</dd><dt>Worker</dt><dd>${e(j.image)}</dd><dt>Review fingerprint</dt><dd>${e(j.fingerprint.slice(0,20))}…</dd></dl>${!state.data.worker.ready?'<div class="callout amber">Docker is not configured on this machine. Approval can be recorded, but execution will stay blocked until a worker is available.</div>':''}</div><div class="review-footer"><small>Approval applies to this exact artifact.</small><div class="row"><button class="btn" data-action="reject">Reject</button><button class="btn primary" data-action="approve">Approve script</button></div></div>`;
if(!j?.result)return `<div class="empty"><div class="empty-icon">${icon('chart',26)}</div><h3>An evidence trail, not just an answer</h3><p>Run a comparison to see response curves,<br> numerical checks, and source provenance.</p></div><div class="panel-body"><div class="checkrow"><span>1. Export through the engineering application</span><span>Local</span></div><div class="checkrow"><span>2. Run a released analysis method</span><span>Deterministic</span></div><div class="checkrow"><span>3. Review results and evidence</span><span>Human decision</span></div></div>`;
return `<div class="tabs">${['results','inputs','evidence'].map(t=>`<button class="tab ${state.tab===t?'active':''}" data-tab="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="panel-body">${state.revisionPrompt?'<div class="callout">What would you like changed? Describe it in the message box. Axis-line display changes are supported; numerical changes require a new reviewed analysis. Your report is still awaiting review.</div>':''}${state.tab==='results'?results(j):state.tab==='inputs'?inputs(j):evidence(j)}</div><div class="review-footer"><small>${j.status==='accepted'?'Accepted by the local demo reviewer.':'Synthetic results · engineer acceptance required'}</small><div class="row">${j.status==='result_review'?'<button class="btn" data-action="request-revision">Request changes</button><button class="btn primary" data-action="approve">Accept report</button>':`<a class="btn" href="/api/jobs/${e(j.id)}/report" download>${icon('download',13)} Export evidence</a>`}</div></div>`}
function results(j){let m=j.result.metrics;return `<div class="chart-title">Response by sample <span class="muted tiny">· a.u.</span></div>${chart(j.result,j.events.some(x=>x.stage==='chart_axes'))}<div class="metrics"><div class="metric"><label>Maximum difference</label><strong>${m.max_abs_delta.toFixed(4)}</strong><small>a.u.</small></div><div class="metric"><label>RMSE</label><strong>${m.rmse.toFixed(4)}</strong><small>a.u.</small></div><div class="metric"><label>Aligned samples</label><strong>${m.samples}</strong><small>pairs</small></div></div><p class="result-narrative">${e(j.narrative)}</p>${j.result.extension?`${extensionChart(j.result)}<div class="callout">${e(j.result.extension.extension)} · ${j.result.extension.points.length} validated samples. Full extension output is included in the evidence download.</div>`:''}${j.result.checks.map(c=>`<div class="checkrow"><span>${e(c.name)}</span><span>✓ Passed</span></div>`).join('')}<div class="callout">${icon('shield',13)} Method and input versions are recorded. No acceptance tolerance has been assumed.</div>${state.data.models.local.configured?'<button class="btn" style="margin-top:15px" data-action="explain">Draft local-model explanation</button>':''}${state.explanation?`<div class="callout"><strong>Local model draft</strong><p>${e(state.explanation)}</p></div>`:''}`}
function inputs(j){return Object.entries(j.inputs).map(([key,r])=>`<h3>Run ${key.toUpperCase()}</h3><dl class="metadata"><dt>Source</dt><dd>${e(r.source_name)}</dd><dt>Reader version</dt><dd>${e(r.reader)}</dd><dt>Schema</dt><dd>${e(r.schema)}</dd><dt>Units</dt><dd>${e(r.x_unit)} / ${e(r.y_unit)}</dd><dt>Source SHA-256</dt><dd>${e(r.source_hash)}</dd></dl>`).join('')+`<div class="callout">The Python service does not parse the binary file. These are the engineering application's exported snapshots.</div>`}
function evidence(j){return `${executionReceipt(j)}<div class="timeline">${j.events.map(x=>`<div><strong>${e(x.stage.replaceAll('_',' '))}</strong>${e(x.detail)}<small>${new Date(x.at*1000).toLocaleString()}</small></div>`).join('')}</div><a class="btn" href="/api/jobs/${e(j.id)}/report" download>${icon('download',13)} Download evidence JSON</a>`}
function jobs(){return head('PERSISTENT WORK','Job history','Resume interrupted work and inspect the decisions behind every result.')+`<div class="panel"><table class="table"><thead><tr><th>Analysis</th><th>Method</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${state.data.jobs.map(j=>`<tr><td>${e(j.request.slice(0,95))}</td><td>${j.extension?'Reviewed extension':'Released comparison'}</td><td>${statusBadge(j.status)}</td><td class="tiny muted">${new Date(j.created*1000).toLocaleString()}</td><td><button class="btn" data-job="${j.id}">Open ${icon('arrow',12)}</button></td></tr>`).join('')||'<tr><td colspan="5">No analyses yet. Start with the sample run comparison.</td></tr>'}</tbody></table></div>`}
function skills(){return head('REUSABLE ENGINEERING','Skills library','Turn accepted work into reviewed, repeatable team capabilities.')+skillProposalForm()+`<div class="banner">Accepted result → proposed skill → release review → reusable workflow. Sharing a recipe does not share its original data.</div><div class="grid3">${state.data.catalog.skills.map(s=>`<div class="card"><div class="row" style="justify-content:space-between"><span class="card-icon">${icon('book',22)}</span>${badge(s.status,s.status==='released'?'green':'amber')}</div><h3>${e(s.name)}</h3><p>${e(s.description)}</p><div class="tiny muted" style="margin-bottom:18px">Version ${e(s.version)} · ${s.job_id?'Derived from accepted work':'Bundled baseline'}</div><div class="row">${s.status==='released'?`<button class="btn primary" data-skill-run="${s.id}">Run skill ${icon('arrow',12)}</button>`:s.status==='candidate'?`<button class="btn primary" data-skill-approve="${s.id}">Approve release</button>`:''}${s.id!=='compare-runs'&&s.status!=='retired'?`<button class="btn" data-skill-retire="${s.id}">Retire</button>`:''}</div></div>`).join('')}</div><div class="callout">Prototype scope: skills reuse the bundled comparison recipe. Moving-average code still needs fresh pre-execution approval. General code packaging and independent release signatures are future integration work.</div>`}
function plugins(){let p=state.data.catalog.plugin;return head('CAPABILITY PACKAGES','Plugins','Bundle an adapter, reviewed routines, skills, and a result view.')+`<div class="grid2"><div class="card"><div class="row" style="justify-content:space-between"><span class="card-icon">${icon('box',24)}</span>${badge(p.enabled?'Enabled':'Disabled',p.enabled?'green':'neutral')}</div><h2 style="margin:18px 0 10px">${e(p.name)}</h2><p>${e(p.description)}</p><dl class="metadata"><dt>Version</dt><dd>${e(p.version)}</dd><dt>Owner</dt><dd>${e(p.owner)}</dd><dt>Tools</dt><dd>${p.tools.map(e).join('<br>')}</dd><dt>Access scope</dt><dd>${p.permissions.map(e).join('<br>')}</dd><dt>Verification</dt><dd>Bundled development package; not enterprise signed</dd></dl><button class="btn ${p.enabled?'':'primary'}" data-action="toggle-plugin">${p.enabled?'Disable package':'Enable package'}</button></div><div class="card"><h3>One narrow integration contract</h3><p>The graph asks for a validated series. The adapter invokes the engineering application, which owns the binary format.</p><div class="stack">${['LangGraph job','Reviewed tool contract','Engineering application adapter','Application-owned binary data'].map((v,i)=>`<div class="banner" style="margin:0">${i+1}. ${v}</div>`).join('')}</div><div class="callout">Disabling the package blocks new jobs and execution. This prototype does not install arbitrary third-party code or claim MCP certification.</div></div></div>`}
function knowledge(){return head('REVIEWED IMPROVEMENT','Knowledge & learning','Retain useful knowledge with explicit scope and review.')+`<div class="grid2"><div class="panel"><div class="panel-head"><h3>Propose a note</h3>${badge('Review required','amber')}</div><div class="panel-body"><p class="muted tiny">Capture a method convention or preference. Notes do not change the model, execution policy, or approved code.</p><label class="form-label" for="memory">Knowledge or preference</label><textarea id="memory" class="text-input" rows="4" placeholder="For example: show RMSE alongside maximum difference in review meetings."></textarea><label class="form-label" for="memory-source">Source or rationale</label><input id="memory-source" class="text-input" maxlength="300" value="User-authored note"><label class="form-label" for="scope">Intended scope</label><select id="scope" class="select"><option value="project">This project</option><option value="personal">Personal</option></select><div style="margin-top:18px"><button class="btn primary" data-action="add-memory">Propose for review</button></div></div></div><div class="card"><h3>A controlled learning loop</h3><p>Observed work → proposed improvement → human review → retained knowledge or a released skill.</p><div class="callout">Approved notes are retrieved by keyword into local conversations with their sources. Retired notes are excluded from new retrievals. This does not train the model or change tool permissions.</div><p class="tiny muted" style="margin-top:20px">Personal and project scopes are labels in this single-user demo. Production requires identity-backed access controls.</p></div></div><div class="section-title"><h2>Retained knowledge</h2></div><div class="stack">${state.data.catalog.knowledge.map(m=>`<div class="card"><div class="row">${badge(m.status,m.status==='approved'?'green':'neutral')}${badge(m.scope)}</div><p style="color:var(--ink);margin-top:12px">${e(m.text)}</p><p class="tiny muted">${e(m.source)} · revision ${m.revision}</p><div class="row">${m.status==='proposed'?`<button class="btn primary" data-memory-approve="${m.id}">Approve note</button>`:''}${m.status!=='retired'?`<button class="btn" data-memory-retire="${m.id}">Retire</button>`:''}</div></div>`).join('')||'<div class="panel empty">No retained knowledge yet. Add a proposal to see the review lifecycle.</div>'}</div>`}
function source(){return head('REUSE BEFORE GENERATION','Source discovery','Inspect the established code path before proposing a new one.')+`<div class="banner">Curated local source · read-only access · execution remains behind released tools</div>${state.source?`<div class="grid2">${state.source.files.map(f=>`<div class="panel"><div class="panel-head"><div><h3>${e(f.name)}</h3><p>${e(f.path)}</p></div>${icon('code')}</div><div class="panel-body"><pre class="source-code">${e(f.content)}</pre><div class="callout">${f.path.endsWith('.cpp')?'The application validates the binary header, sample count, finite numbers, and ordering before export.':'This released function verifies alignment and units, then computes the comparison directly.'}</div></div></div>`).join('')}</div>`:'<div class="empty">Loading the source catalog…</div>'}`}
function governance(){return head('POLICY TO EXECUTION','Governance','Make the trust boundary visible at every step.')+`<div class="grid3"><div class="card"><span class="card-icon">${icon('shield',24)}</span><h3>Engineering stays local</h3><p>Internet inference is disabled. Model destinations and external evidence folders require server-side configuration; LAN destinations require explicit approval. OS-level isolation remains a deployment requirement.</p>${badge('Enforced in this prototype','green')}</div><div class="card"><span class="card-icon">${icon('code',24)}</span><h3>Review before execution</h3><p>A script approval is tied to the code, input snapshots, worker image, and scope. Generated code has no host-execution fallback.</p>${badge('Separate review checkpoint','green')}</div><div class="card"><span class="card-icon">${icon('file',24)}</span><h3>Evidence before acceptance</h3><p>Calculations, validation checks, input hashes, and review decisions accompany the result. Model text is always a draft.</p>${badge('Local evidence history','green')}</div></div><div class="section-title"><h2>Where this fits in the enterprise</h2></div><div class="panel"><table class="table"><thead><tr><th>Capability</th><th>Purpose</th><th>Boundary</th></tr></thead><tbody><tr><td>Microsoft Copilot</td><td>Approved productivity and document work</td><td>Existing corporate policy and tenant controls</td></tr><tr><td>GitHub Copilot</td><td>Approved software development assistance</td><td>Existing repository and development policies</td></tr><tr><td>Engineering AI Workbench</td><td>Engineering execution and reviewed results</td><td>Local data, scoped application tools, explicit approvals</td></tr></tbody></table></div><div class="callout amber">This is a single-user prototype, not an enterprise security boundary. SSO, per-user authorization, tamper-resistant audit storage, signed plugin distribution, and production Windows deployment remain to be implemented.</div>`}
function models(){const m=state.data.models,w=state.data.worker;return head('REPLACEABLE INTELLIGENCE','Model connections','Keep model selection separate from data access and execution authority.')+`<div class="grid2"><div class="card"><span class="card-icon">${icon('settings',22)}</span><h3>Local / approved on-premises model</h3><p>Powers conversations, proposes analysis plans, drafts reviewed Python, and explains computed metrics. Calculations use the released tools.</p>${badge(m.local.configured?'Configured':'Optional · not configured',m.local.configured?'green':'neutral')}<dl class="metadata"><dt>Model</dt><dd>${e(m.local.model)}</dd><dt>Interface</dt><dd>OpenAI-compatible chat completions</dd><dt>Setup</dt><dd>Server environment configuration; see README</dd></dl></div><div class="card"><span class="card-icon">${icon('cloud',22)}</span><h3>Frontier general reasoning</h3><p>Internet inference is disabled by the offline policy, including public general-reasoning questions.</p>${badge(m.frontier.configured?'Configured':'Blocked by offline policy',m.frontier.configured?'green':'neutral')}<label class="form-label" for="topic">Public topic</label><select class="select" id="topic"><option value="rmse">RMSE vs. maximum difference</option><option value="validation">General validation principles</option><option value="sampling">Sample alignment</option></select><div style="margin-top:14px"><button class="btn" data-action="general" ${!m.frontier.configured?'disabled':''}>Ask general question</button></div></div></div>${state.general?`<div class="card" style="margin-top:20px"><h3>Public reasoning response</h3><p style="white-space:pre-wrap">${e(state.general)}</p></div>`:''}<div class="section-title"><h2>Isolated Python worker</h2></div><div class="panel panel-body"><div class="row">${badge(w.ready?'Configured':'Not ready',w.ready?'green':'amber')}<span class="tiny muted">${w.docker_installed?'Docker command found':'Docker is not installed'} · ${w.image_configured?'Image configured':'No approved image selected'}</span></div><p class="subtitle">Fresh container · no network · read-only inputs · non-root · pinned image · bounded memory and runtime</p><div class="callout">No LLM is bundled or downloaded automatically. The guided demonstration works without one. See the setup guide to connect your approved endpoints and enable the Python worker.</div></div>`}
const pages={workbench,jobs,skills,plugins,knowledge,source,governance,models};
async function openJob(id){state.job=await api('/jobs/'+id);state.page='workbench';state.tab='results';state.explanation='';render()}
async function run(request,workflow){state.busy=true;render();try{const r=await api('/jobs',{request,workflow});state.draft='';await openJob(r.id);await refresh()}finally{state.busy=false;render()}}
document.addEventListener('input',ev=>{if(ev.target.id==='request')state.draft=ev.target.value});
document.addEventListener('change',ev=>{if(ev.target.id==='workflow')state.workflow=ev.target.value});
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;try{
if(b.dataset.page){state.page=b.dataset.page;render();if(state.page==='source'&&!state.source){state.source=await api('/source');render()}return}
if(b.dataset.job)return await openJob(b.dataset.job);
if(b.dataset.tab){state.tab=b.dataset.tab;render();return}
if(b.dataset.example){state.workflow=b.dataset.example;state.draft=state.workflow==='compare'?'Compare Run A against Run B and prepare a difference report.':'Compare the runs and calculate a five-sample moving-average difference.';render();return}
if(b.dataset.skillRun){const r=await api('/skills/'+b.dataset.skillRun+'/run',{});await openJob(r.id);return}
for(const [key,path,action] of [['skillApprove','skills','approve'],['skillRetire','skills','retire'],['memoryApprove','knowledge','approve'],['memoryRetire','knowledge','retire']])if(b.dataset[key]){await api('/'+path+'/'+b.dataset[key]+'/decision',{action,...(path==='knowledge'?{revision:state.data.catalog.knowledge.find(m=>m.id===b.dataset[key]).revision}:{})});await refresh();toast('Review decision saved');return}
const action=b.dataset.action;if(!action)return;
if(action==='new'){state.job=null;state.page='workbench';state.draft='';state.explanation='';render()}
if(action==='run'){if(!state.draft.trim())return toast('Enter a request or choose one of the examples.');await run(state.draft,state.workflow)}
if(['approve','reject','resume','cancel'].includes(action)){b.disabled=true;await api('/jobs/'+state.job.id+'/action',{action,fingerprint:state.job.status==='code_review'?state.job.fingerprint:state.job.result_fingerprint||''});await refresh()}
if(action==='request-revision'){state.revisionPrompt=true;render();document.querySelector('#request')?.focus();toast('Describe the change in the message box. The report remains awaiting review.');return}
if(action==='promote'){state.skillProposal={job_id:state.job.id};state.page='skills';render()}
if(action==='cancel-skill-proposal'){state.skillProposal=null;render()}
if(action==='save-skill-proposal'){const name=document.querySelector('#skill-name').value.trim();if(!name)return toast('Name this skill first.');await api('/skills',{job_id:state.skillProposal.job_id,name});state.skillProposal=null;await refresh();toast('Skill proposed. A separate release decision is required.')}
if(action==='add-memory'){const text=document.querySelector('#memory').value.trim(),scope=document.querySelector('#scope').value;if(!text)return toast('Write a note first.');await api('/knowledge',{text,scope,source:document.querySelector('#memory-source').value});await refresh();toast('Note proposed for review')}
if(action==='toggle-plugin'){await api('/plugin',{enabled:!state.data.catalog.plugin.enabled});await refresh()}
if(action==='explain'){b.disabled=true;const r=await api('/jobs/'+state.job.id+'/explain',{});state.explanation=r.text;render()}
if(action==='general'){const topic=document.querySelector('#topic').value;b.disabled=true;const r=await api('/general-reasoning',{topic});state.general=r.text;render()}
}catch(err){toast(err.message);b.disabled=false}});
refresh().catch(err=>{document.querySelector('#app').innerHTML='<div class="loading">Unable to connect to the local workbench. Reload after starting the server.</div>';toast(err.message)});
setInterval(async()=>{if(!state.data)return;if(['workbench','workflows'].includes(state.page)&&state.job&&['queued','running'].includes(state.job.status)){try{await refresh()}catch(err){toast('Connection interrupted. The job checkpoint is retained.')}}},900);

function executionReceipt(j){const r=j.result?.extension?.execution;if(!r)return j.extension?'<div class="callout">This older run predates execution receipts. New extension runs include Docker identity and exit status.</div>':'';return `<div class="callout"><strong>Docker execution confirmed</strong><dl class="metadata"><dt>Container</dt><dd>${e(r.container_name)}</dd><dt>Image</dt><dd>${e(r.image_id)}</dd><dt>Exit status</dt><dd>${r.exit_code} · success</dd><dt>Duration</dt><dd>${(r.finished_at-r.started_at).toFixed(2)} seconds</dd><dt>Isolation</dt><dd>No network · non-root · ${r.memory_mb} MB</dd><dt>Cleanup</dt><dd>Container removed after completion</dd><dt>Script SHA-256</dt><dd>${e(r.script_sha256)}</dd></dl></div>`}

function extensionChart(result){
 const raw=result.delta,smooth=result.extension.points,pts=[...raw,...smooth];
 let lo=Math.min(...pts.map(p=>p[1])),hi=Math.max(...pts.map(p=>p[1]));const pad=(hi-lo||1)*.12;lo-=pad;hi+=pad;
 const xmin=raw[0][0],xmax=raw[raw.length-1][0];
 const X=x=>48+(x-xmin)/(xmax-xmin)*396,Y=y=>150-(y-lo)/(hi-lo)*126;
 const path=series=>series.map((p,i)=>`${i?'L':'M'}${X(p[0]).toFixed(2)},${Y(p[1]).toFixed(2)}`).join(' ');
 return `<div class="chart-title" style="margin-top:24px">Difference before and after smoothing · a.u.</div><svg class="chart" viewBox="0 0 470 190" role="img" aria-label="Raw difference and validated five-sample moving average">${Array.from({length:4},(_,i)=>{const y=lo+(hi-lo)*i/3;return `<line x1="48" y1="${Y(y)}" x2="444" y2="${Y(y)}" stroke="#edf1f1"/><text x="40" y="${Y(y)+3}" text-anchor="end" fill="#8b9ca0" font-size="9">${y.toFixed(3)}</text>`}).join('')}<path d="${path(raw)}" fill="none" stroke="#9cabc0" stroke-width="1.5" stroke-dasharray="4 3"/><path d="${path(smooth)}" fill="none" stroke="#078a8c" stroke-width="2"/><text x="246" y="178" text-anchor="middle" fill="#8b9ca0" font-size="9">Sample ${xmin} to ${xmax}</text></svg><div class="legend"><span><i class="blue"></i>Raw B minus A</span><span><i></i>Five-sample average</span></div>`;
}

function skillProposalForm(){return state.skillProposal?`<section class="panel panel-body" style="margin-bottom:22px"><h3>Propose a reusable skill</h3><p class="subtitle">This creates a candidate recipe from the accepted analysis. Release requires a separate review.</p><label class="form-label" for="skill-name">Skill name</label><input id="skill-name" class="text-input" maxlength="80" value="Response comparison review"><div class="code-actions"><button class="btn" data-action="cancel-skill-proposal">Cancel proposal</button><button class="btn primary" data-action="save-skill-proposal">Propose skill</button></div></section>`:''}
