state.configuration=null;
async function loadConfiguration(){state.configuration=await api('/configuration')}
pages.models=function(){const c=state.configuration;if(!c)return head('SETTINGS','Models & runtime','Open this page to load configuration.');const d=state.connectionEdit||{};return head('SETTINGS','Models & runtime','Configure saved model connections and local Docker execution.')+`<div class="callout">All local-mode agents use the active connection. Providers must support OpenAI-compatible chat completions. Internet endpoints remain blocked; LAN endpoints require administrator approval. Credentials remain server-managed.</div><div class="panel panel-body"><h3>${d.id?'Edit':'Add'} model connection</h3><label class="form-label">Name</label><input class="text-input" id="conn-name" value="${e(d.name||'')}"><label class="form-label">Provider</label><select id="conn-provider" class="select">${['Ollama','LM Studio','OpenAI-compatible'].map(x=>`<option ${d.provider===x?'selected':''}>${x}</option>`).join('')}</select><label class="form-label">API base URL (including /v1)</label><input class="text-input" id="conn-url" value="${e(d.url||c.current_url||'http://127.0.0.1:11434/v1')}"><label class="form-label">Model name</label><input class="text-input" id="conn-model" value="${e(d.model||c.current_model||'')}"><button class="btn primary" data-config-save>Save connection</button><button class="btn" data-config-new>Clear form</button></div>${c.connections.map(x=>`<div class="card"><h3>${e(x.name)} ${c.active===x.id?badge('Active','green'):''}</h3><p>${e(x.provider)} · ${e(x.model)}</p><button class="btn" data-conn-edit="${x.id}">Edit</button><button class="btn" data-conn-id="${x.id}" data-conn-action="test">Test connection</button><button class="btn" data-conn-id="${x.id}" data-conn-action="activate">Use model</button></div>`).join('')}<section class="panel panel-body"><h3>Docker runtime</h3><p>Uses the local Docker context. Remote Docker is blocked. No images are downloaded.</p><label class="form-label">Comparison image ID</label><input class="text-input" id="runtime-comparison" value="${e(c.comparison_image)}"><label class="form-label">Dynamic Python image ID</label><input class="text-input" id="runtime-python" value="${e(c.python_image)}"><button class="btn" data-runtime-test>Test Docker</button><button class="btn primary" data-runtime-save>Verify and save images</button></section>`};
pages.governance=function(){const c=state.configuration;return head('SETTINGS','Security & permissions','Manage access without changing the mandatory execution boundaries.')+`<div class="panel panel-body"><h3>Resource inspection</h3><p>${c?.discovery_disabled?'Disabled':'Enabled only within administrator-approved roots'}</p><pre>${e(JSON.stringify(c?.resource_roots||[],null,2))}</pre><button class="btn" data-page="data-sources">Manage data registrations</button><button class="btn" data-page="source">Manage source registrations</button><button class="btn" data-security-disable ${c?.discovery_disabled?'disabled':''}>Disable resource inspection</button><p class="tiny muted">Disable takes effect immediately and persists. Restoration and expanding approved roots require administrator configuration.</p></div><div class="panel panel-body"><h3>Enforced boundaries</h3><p>Internet model calls blocked. Generated Python requires exact-script approval and isolated Docker execution. These protections cannot be disabled here.</p><p>Approved model IPs: ${e(c?.approved_model_ips||'None')}</p><button class="btn" data-page="agents">Manage agent tool permissions</button><button class="btn" data-page="plugins">Manage package enablement</button><p class="tiny muted">Single-user prototype. Operating-system permissions and firewall controls remain necessary.</p></div>`};
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;try{
if(['models','governance'].includes(b.dataset.page)){await loadConfiguration();render()}
if(b.hasAttribute('data-config-new')){state.connectionEdit=null;render()}
if(b.dataset.connEdit){state.connectionEdit=state.configuration.connections.find(x=>x.id===b.dataset.connEdit);render()}
if(b.hasAttribute('data-config-save')){await api('/connections'+(state.connectionEdit?.id?'/'+state.connectionEdit.id:''),{name:document.querySelector('#conn-name').value,provider:document.querySelector('#conn-provider').value,url:document.querySelector('#conn-url').value,model:document.querySelector('#conn-model').value});state.connectionEdit=null;await loadConfiguration();render();toast('Saved. Use model to activate this configuration.')}
if(b.dataset.connAction){b.disabled=true;const r=await api('/connections/'+b.dataset.connId+'/action',{action:b.dataset.connAction});await loadConfiguration();await refresh();toast(r.message)}
if(b.hasAttribute('data-runtime-test')){b.disabled=true;toast((await api('/runtime/test',{})).message);b.disabled=false}
if(b.hasAttribute('data-runtime-save')){const r=await api('/runtime',{comparison_image:document.querySelector('#runtime-comparison').value,python_image:document.querySelector('#runtime-python').value});await loadConfiguration();await refresh();toast(r.message)}
if(b.hasAttribute('data-security-disable')){toast((await api('/security/disable-discovery',{})).message);await loadConfiguration();render()}
}catch(err){toast(err.message);b.disabled=false}});
