state.resources=[];
function resourcePage(category){const source=category==='source';return head(source?'REUSE BEFORE GENERATION':'ANALYSIS INPUTS',source?'Source discovery':'Data sources',source?'Register code folders or files, then inspect approved locations.':'Register datasets and their engineering meaning.')+`<div class="callout">Registration does not grant filesystem access. An administrator must configure approved resource roots before inspection. No internet fetches, compilation, or execution. ${source?'Inspection provides a read-only preview; automatic model retrieval is not connected yet.':'CSV supports bounded preview. Binary, HDF5 and databases require reader integrations. Attaching these sources to analysis tasks is not connected yet.'}</div><section class="panel panel-body"><h3>Add ${source?'source location':'data source'}</h3><label class="form-label">Name</label><input id="resource-name" class="text-input"><label class="form-label">${source?'Absolute code folder or file path':'Location or connection reference — no credentials'}</label><input id="resource-location" class="text-input"><label class="form-label">Description</label><input id="resource-description" class="text-input">${source?'':`<label class="form-label">Format</label><select id="resource-format" class="select"><option value="csv">CSV</option><option value="binary">Application binary</option><option value="hdf5">HDF5</option><option value="sql">Database</option><option value="other">Other</option></select><label class="form-label">Units and schema notes</label><input id="resource-units" class="text-input"><label class="form-label">Approved reader or tool reference</label><input id="resource-reader" class="text-input">`}<button class="btn primary" data-resource-add="${category}">Register location</button></section><div class="stack">${state.resources.filter(r=>r.category===category).map(r=>`<section class="card"><h3>${e(r.name)}</h3><p>${e(r.location)}</p><p>${e(r.description)}</p>${badge(r.format)}<button class="btn" data-resource-inspect="${r.id}">Inspect</button><button class="btn" data-resource-remove="${r.id}">Remove registration</button>${state.resourcePreview?.id===r.id?`<pre class="source-code">${e(JSON.stringify(state.resourcePreview.result,null,2))}</pre>`:''}</section>`).join('')}</div>`}
pages.source=()=>resourcePage('source');pages['data-sources']=()=>resourcePage('data');
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{
if(['source','data-sources'].includes(b.dataset.page)){state.resources=await api('/resources');render()}
if(b.dataset.resourceAdd){const source=b.dataset.resourceAdd==='source';await api('/resources',{category:b.dataset.resourceAdd,name:document.querySelector('#resource-name').value,location:document.querySelector('#resource-location').value,description:document.querySelector('#resource-description').value,format:source?'code':document.querySelector('#resource-format').value,units:source?'':document.querySelector('#resource-units').value,reader:source?'':document.querySelector('#resource-reader').value});state.resources=await api('/resources');render();toast('Location registered; access permissions are unchanged')}
if(b.dataset.resourceInspect){state.resourcePreview={id:b.dataset.resourceInspect,result:await api('/resources/'+b.dataset.resourceInspect+'/inspect',{})};render()}
if(b.dataset.resourceRemove){await api('/resources/'+b.dataset.resourceRemove+'/remove',{});state.resources=await api('/resources');render()}
}catch(err){toast(err.message)}});
